import logging
from pathlib import Path

from api.collection.test_sets import delete_test_case, get_test_generators, get_test_set
from api.execution.execute_python import run_python_file
from api.jobs import update_job
from api.models.problem import (
    GenerateMultipleTestsRequest,
    TestGenerator,
)


def run_testgen_job(
    problem_path: Path, req: GenerateMultipleTestsRequest, job_id: str
) -> None:
    """
    Background task: runs all applicable validators and streams partial results
    into the job cache file roughly every _FLUSH_INTERVAL seconds.

    Intended to be registered with FastAPI BackgroundTasks:

        bg.add_task(run_validators_job, problem_path, req, job_id)
    """
    try:
        update_job(job_id, status="running")

        generators = get_test_generators(problem_path)

        results = []

        any_failed = False

        for generator in generators:
            if any(
                r.test_set == generator.test_set and r.generator_name == generator.name
                for r in req.requests
            ):
                results.append(
                    {
                        "test_set": generator.test_set,
                        "generator_name": generator.name,
                        "status": "PENDING",
                    }
                )
                update_job(
                    job_id,
                    result=results,
                )

                # Remove all files generated by this generator
                remove_testgen_files(problem_path, generator)

                try:
                    res = run_individual_testgen(problem_path, generator)
                    results[-1]["status"] = "COMPLETE"
                    results[-1]["output"] = res.stdout
                except Exception as e:
                    import traceback

                    results[-1]["status"] = "FAILED"
                    results[-1]["error"] = traceback.format_exc()

                    any_failed = True

                update_job(
                    job_id,
                    result=results,
                )

        update_job(
            job_id,
            status="failed" if any_failed else "done",
            result=results,
        )

    except Exception as exc:
        import traceback

        logging.error(traceback.format_exc())
        update_job(job_id, status="failed", error=str(exc))
        raise


def remove_testgen_files(problem_path: Path, test_generator: TestGenerator):
    test_set = get_test_set(problem_path, test_generator.test_set)
    for case in test_set.test_cases:
        if case.generated_by == str(test_generator.relative_path()):
            # Delete the case
            delete_test_case(problem_path, case.set_name, case.name)


def run_individual_testgen(problem_path: Path, test_generator: TestGenerator):
    generator_file = test_generator.full_path(problem_path)

    res = run_python_file(generator_file, None, timeout_sec=None)
    if res.exit_code != 0:
        raise ValueError(res.stderr)
    return res
