author: Jackson Goerner
difficulty: 800
export_config:
  mcpc-problems:
    location: ~/Desktop/mcpc-problems/problems
    dmoj_config: {}
    type: dmoj
    clear_directory: true
limits:
  memory: 262144
  time: 1
name: Maximum of a List
state: in-progress
tags:
- implementation
type: standard
contests:
- special26
